### ISSUE TITLE
[ISSUE] Food and Hunger Info Bar won't go away.

### ISSUE THREAD

**Issue by Nightmare-Night** [Underscore-Gaming/28DaysLaterBugTracker#2]
# General Information
Your SteamID: STEAM_0:0:57599947
Name on the Server: Nightmare Night
Date of occurence: N/A
Time of occurence (including timezone!): N/A

# Specific Information
Specify what type of bug this is (Item/Environmental/Mechanic): Mechanic
Where did this happen?: Info Bars and Settings
What were you doing when it happened?: Changing Settings
Explain the issue in as much detail as you can: For the two info bars set by the survival plugin, it doesn't check for if the config option `alwaysShowBars` is true or false. This causes this issue as far as I know.
Anything else we should know?: I dunno

# Console logs
Post console logs of the error here, to help us track down the issue faster.
N/A

# Version ID: Latest
This can be gathered by checking the recent updates section. If this issue occurred weeks after the latest version, just add "Latest".

**Comment by JakeDaBoss** [comment]
Forgotten field added now. Please fill in the new field.

**Comment by Nightmare-Night** [comment]
Updated @JakeDaBoss

**Comment by JakeDaBoss** [comment]
Due to the architecture of this plugin, it's unable to be fixed by me, as it would entail rewriting/writing a lot of things, which isn't advisable for the time being. Issue closed.
